# Generated by Django 3.2 on 2021-04-20 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restauthn', '0002_alter_authenticator_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticator',
            options={'verbose_name': 'Authenticator', 'verbose_name_plural': 'Authenticators'},
        ),
        migrations.AddField(
            model_name='authenticator',
            name='name',
            field=models.CharField(default='titanbt', max_length=100, verbose_name='Nickname'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='authenticator',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expires', models.DateTimeField(verbose_name='Expires')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
